# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90f73d1ef472999bcfa0da0fd35ecbbb29877466dab6eef73de0a01271dd541cd6936e07fad3f25e0e14f0f3645a88295baa5181a095be9589fc5ccc63fa211d

test:
  secret_key_base: e742b71affe5ca70ca450c5a3c1788799e59994523a9f9a4bf49365c7a062ad4d915371c2768e364ce69660aee7f1948836685c92e2087087ce679b1be6a1036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
